# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab3():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab3(self):
    self.driver.get("https://tutorialsninja.com/demo/")
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "#input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH, "(//div[@class=\'product-thumb\']//button[contains(@onclick,\'cart.add\')])[1]")))
    self.driver.find_element(By.XPATH, "(//div[@class=\'product-thumb\']//button[contains(@onclick,\'cart.add\')])[1]").click()
    WebDriverWait(self.driver, 3).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".alert-success")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert-success").text == "Success: You have added iMac to your shopping cart! ×"
  